version: '3.8'

networks:
  ingress:
    name: ingress
    external: true

services:

  ai-agent:
    image: ghcr.io/nocoders/korean-teacher-agent:latest
    build:
      context: ./src/korean-teacher-agent
      dockerfile: Dockerfile
    container_name: ai-agent
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.ai-agent.rule=Host(`ai-agent.${DOMAIN}`)
      - traefik.http.services.ai-agent.loadbalancer.server.port=8000
      - traefik.http.routers.ai-agent.entrypoints=websecure
      - traefik.http.routers.ai-agent.tls=true

    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
    volumes:
      - ./src/korean-teacher-agent/:/app
      - ai-agent-data:/data
    working_dir: /app
    command: poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - ingress
  phoenix:
    image: arizephoenix/phoenix:latest # Must be greater than 4.0 version to work
    container_name: phoenix
    ports:
      - 6006:6006  # PHOENIX_PORT
      - 4317:4317  # PHOENIX_GRPC_PORT
      - 9090:9090  # [Optional] PROMETHEUS PORT IF ENABLED
    environment:
      - PHOENIX_WORKING_DIR=/mnt/data
      - PHOENIX_PORT=6006
    volumes:
      - phoenix_data:/mnt/data   # PHOENIX_WORKING_DIR
    labels:
      - traefik.enable=true
      - traefik.http.routers.phoenix.rule=Host(`phoenix.${DOMAIN}`)
      - traefik.http.services.phoenix.loadbalancer.server.port=6006
      - traefik.http.routers.phoenix.entrypoints=websecure
      - traefik.http.routers.phoenix.tls=true

    networks:
      - ingress

volumes:
  ai-agent-data:
    external: false
  phoenix_data:
    driver: local
