---
networks:
  ingress:
    name: ingress
    external: true

services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    labels:
      - traefik.enable=true
      - traefik.http.routers.dozzle.entrypoints=websecure
      - traefik.http.routers.dozzle.rule=Host(`dozzle.${DOMAIN}`)
      - traefik.http.services.dozzle.loadbalancer.server.port=8080
    ports:
      - 18888:8080
    environment:
      DOZZLE_AUTH_PROVIDER: simple
      DOZZLE_AUTH_TTL: 48h
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./users.yml:/data/users.yml
    networks:
      - ingress
    restart: always