---
networks:
  ingress:
    name: ingress
    external: true

volumes:
  nocodb_data: {}
  nocodb_db: {}

services:
  nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb
    environment:
      # - NC_DB=pg://nocodb-db:5432?u=${NOCODB_DATABASE_USER}&p=${NOCODB_DATABASE_PW}&d=${NOCODB_DATABASE_NAME}
      - NC_PUBLIC_URL=https://nocodb.${DOMAIN}
      - NC_DISABLE_TELE=true
      # SQLite 
      # - LITESTREAM_S3_ENDPOINT=${LITESTREAM_S3_ENDPOINT}
      - LITESTREAM_S3_REGION=${LITESTREAM_S3_REGION}
      - LITESTREAM_S3_BUCKET=${LITESTREAM_S3_BUCKET}
      - LITESTREAM_S3_ACCESS_KEY_ID=${LITESTREAM_S3_ACCESS_KEY_ID}
      - LITESTREAM_S3_SECRET_ACCESS_KEY=${LITESTREAM_S3_SECRET_ACCESS_KEY}
      # Object Storage
      - NC_S3_BUCKET_NAME=${NC_S3_BUCKET_NAME}
      - NC_S3_REGION=${NC_S3_REGION}
      # - NC_S3_ENDPOINT=${NC_S3_ENDPOINT}
      - NC_S3_ACCESS_KEY=${NC_S3_ACCESS_KEY}
      - NC_S3_ACCESS_SECRET=${NC_S3_ACCESS_SECRET}
      - NC_ATTACHMENT_FIELD_SIZE=${NC_ATTACHMENT_FIELD_SIZE}
      # SMTP
      - NC_SMTP_FROM=${EMAIL}
      - NC_SMTP_HOST=${NC_SMTP_HOST}
      - NC_SMTP_PORT=${NC_SMTP_PORT}
      - NC_SMTP_USERNAME=${NC_SMTP_USERNAME}
      - NC_SMTP_PASSWORD=${NC_SMTP_PASSWORD}
      - NC_SMTP_SECURE=true

    labels:
      - traefik.enable=true
      - traefik.http.routers.nocodb.entrypoints=websecure
      - traefik.http.routers.nocodb.rule=Host(`nocodb.${DOMAIN}`)
      - traefik.http.services.nocodb.loadbalancer.server.port=8080
    networks:
      - ingress
    volumes:
      - nocodb_data:/usr/app/data
    restart: always
