"""initial migration

Revision ID: 8e32f0b4b90c
Revises: 
Create Date: 2025-06-07 13:05:00.574222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e32f0b4b90c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homework',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('initial_request', sa.Text(), nullable=False),
    sa.Column('homework_topic', sa.String(length=255), nullable=True),
    sa.Column('homework_writing_type', sa.String(length=100), nullable=True),
    sa.Column('homework_keywords', sa.Text(), nullable=True),
    sa.Column('detailed_homework', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('homework_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homework_id'), 'homework', ['id'], unique=False)
    op.create_index(op.f('ix_homework_status'), 'homework', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_homework_status'), table_name='homework')
    op.drop_index(op.f('ix_homework_id'), table_name='homework')
    op.drop_table('homework')
    # ### end Alembic commands ###
