"""Add user feedback table

Revision ID: e26cf6e98228
Revises: 6ba4f358c0e8
Create Date: 2025-06-07 22:41:59.981620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e26cf6e98228'
down_revision: Union[str, None] = '6ba4f358c0e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homework', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thread_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_homework_thread_id'), ['thread_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homework', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_homework_thread_id'))
        batch_op.drop_column('thread_id')

    # ### end Alembic commands ###
